#!/bin/bash
docker tag $IMAGE_NAME $DOCKER_REPO:${SOURCE_COMMIT:0:8}
docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:${SOURCE_COMMIT:0:8}
docker push $DOCKER_REPO:latest
docker push $IMAGE_NAME
